### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by sayler8182** [congnd/FMPhotoPicker#18]
Do you plan to add support for picking **video** like in system picker? 
I mean smth like this:
`func fmPhotoPickerController(_ picker: FMPhotoPickerViewController, didFinishPickingVideoWith videos: [URL]) { }`

**Comment by n-cong** [comment]
@stakada7 
How do you think about this idea?

**Comment by stakada7** [comment]
@sayler8182
Thank you issues.

We didn't plan to add video support.
but, video support is an awesome idea.

**Comment by stakada7** [comment]
@ n-cong
Hi.
By the way, we need an owner of this repository.

We do not use this repository for our products, now.
Therefore, we can not plan repository milestones ...

My suggestion is the following two.
Which suggestion do you think is good?

1. This repository close.
2. Recruit people who fork the repository

regards.

**Comment by congnd** [comment]
@stakada7 
(I'm Cong, this is my personal account)
Thanks for the response. 

Some people are using this library in their product. So I don't think closing this repository is a good idea. If you want to have a maintainer for this library, you can believe in me. I'm very happy to handle every issue regarding this library since I'm the creator of it.

In case you want to do so, please set me as a maintainer of this repository.
My account: congnd

Thanks

**Comment by stakada7** [comment]
@congnd 
ok. It's nice. I hope so.

I think FMPhotoPicker is an awesome library. many users need support for FMPhotoPicker.
and I hope more growing up FMPhotoPicker.

I added you a collaborator.
plz, check it.

I am very happy if you are the maintainer of FMPhotoPicker.

thank you sooooooo much.

regards.

**Comment by congnd** [comment]
Hi @sayler8182 

Sorry for the late reply.

Thank you for the great idea. In fact, video viewer function is already supported in the core of FMPhotoPicker. So I think supporting video picking is not so hard for now. I will seriously consider doing it and inform you when I have an update.

**Comment by unixb0y** [comment]
Is there anything new about that?

**Comment by congnd** [comment]
With the new release, getting selected videos now becomes possible. Please checkout v1.3.0
https://github.com/congnd/FMPhotoPicker/releases/tag/1.3.0
