### ISSUE TITLE
Not support video?

### ISSUE THREAD

**Issue by iOSSer** [congnd/FMPhotoPicker#24]
it's detail said support video, but it's delegate just return `photos: [UIImage]`,  i hope it's support  images and videos

**Comment by congnd** [comment]
I'm sorry, I'm working on that...

**Comment by barisnurlu** [comment]
Hi @congnd is there any news on that?

**Comment by congnd** [comment]
With the new release, getting selected videos now becomes possible. Please checkout v1.3.0
https://github.com/congnd/FMPhotoPicker/releases/tag/1.3.0
