### ISSUE TITLE
Could not load the "check_on" image referenced from a nib in the bundle with identifier "someID"

### ISSUE THREAD

**Issue by hyouuu** [congnd/FMPhotoPicker#27]
The xcassets couldn't be loaded in the main app target, and there seems to be ways around it: https://stackoverflow.com/questions/33063233/cant-load-images-from-xcasset-in-cocoapods

**Comment by hyouuu** [comment]
Also, the UI loads up very slowly - not sure if it's related to resource not loading issue though

**Comment by n-cong** [comment]
@hyouuu 
Could you provide a demo project for this issue?

**Comment by congnd** [comment]
@hyouuu 
Could you provide a demo project for this issue?

**Comment by hyouuu** [comment]
This problem should show with any project that integrates FMPhotoPicker with CocoaPod on Xcode 10.2.1

**Comment by congnd** [comment]
Xcode 10.2.1 is quite old now, so let me close this issue.
Feel free to open it again when you have the same issue on the newest version of Xcode
