### ISSUE TITLE
Hide Edit Button

### ISSUE THREAD

**Issue by iFallen** [congnd/FMPhotoPicker#32]
How to hide Edit Button , disable photo edit ,just show origin image

**Comment by congnd** [comment]
@iFallen 
With the release of v1.0.0, you are now able to hide the edit button by setting both the `avaiableCrops` and `avaiableFilters` to `nil`.

Read the documentation herer for more detail:
https://github.com/congnd/FMPhotoPicker#ref-available-crops

Feel free to reopen this a gain if you need more support.
