### ISSUE TITLE
crash in FMLoadingView

### ISSUE THREAD

**Issue by engsulta** [congnd/FMPhotoPicker#34]
crash fix replace old init method with this one 
private init() {
        if let rootVC = (UIApplication.shared.windows.first?.rootViewController) {
            self.transparentView = UIView(frame: rootVC.view.frame)
            
        } else {
            let windowFrame = UIApplication.shared.keyWindow?.frame
            self.transparentView = UIView(frame: windowFrame ?? .zero)
        }
        
        self.transparentView.backgroundColor = UIColor(white: 0, alpha: 0.4)
        
        self.indicator = UIActivityIndicatorView(frame: CGRect(x: 0, y: 0, width: 35, height: 35))
        self.indicator.center = self.transparentView.center
        self.indicator.color = .white
        
        self.transparentView.addSubview(self.indicator)
    }

**Comment by congnd** [comment]
How can I reproduce the crash?

**Comment by congnd** [comment]
Close for long time no response. 
Feel free to reopen it again if you still need supports.

**Comment by naveedmcs** [comment]
--FMWarningView 
   
    let rootVC = (UIApplication.shared.delegate?.window??.rootViewController)! 
    crashed 
Thread 1: Swift runtime failure: force unwrapped a nil value

**Comment by naveedmcs** [comment]
here is the solution 
-------
 comment this line 
  // let rootVC = (UIApplication.shared.delegate?.window??.rootViewController)!
  // update line number 30 with this below line   
  self.containerView = UIView(frame: UIScreen.main.bounds)
