### ISSUE TITLE
Extension for Rotate Image

### ISSUE THREAD

**Issue by Manibhushan393** [congnd/FMPhotoPicker#40]

**Comment by congnd** [comment]
Could you give me more details?

**Comment by Manibhushan393** [comment]
check this screen..i am asking this rotate image feature code.. now in
library showing empty function

**Comment by congnd** [comment]
@Manibhushan393 
Do you mean you want to have image rotation feature?

**Comment by congnd** [comment]
Close due to long time no response.

Feel free to reopen it again if you still need support.
