### ISSUE TITLE
Could not load NIB in bundle

### ISSUE THREAD

**Issue by Ksen17** [congnd/FMPhotoPicker#42]
When trying to present FMPhotoPickerViewController got an error 

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/3AFB974F-E9E0-4678-864B-5716806E8E46/Tuja.app> (loaded)' with name 'FMPhotoPickerViewController''
*** First throw call stack:
(0x1aeb8d5f0 0x1ae8afbcc 0x1aea83b28 0x1b28ccd5c 0x1b25f686c 0x1b25f72e4 0x1b25f759c 0x1b25f7ca0 0x1b260d31c 0x1b260610c 0x1b2607b08 0x1b260a014 0x1b260a51c 0x1b2609f64 0x1b260a1d0 0x102743f94 0x102746240 0x102740e30 0x1e605712c 0x1e6140924 0x1e633fdec 0x1e61b62ac 0x1e61b62c8 0x1e61b62ac 0x1e61a9cfc 0x1e61a98a8 0x1e61e6068 0x1e64a25b8 0x1e64a2800 0x1e64a2e14 0x1b2815380 0x1b2cb8bf0 0x1b280ae5c 0x1b280af6c 0x1b280add4 0x1b2c749fc 0x1b2c506a0 0x1b2cd0d84 0x1b2cd38bc 0x1b2ccb8d0 0x1aeb0bb64 0x1aeb0babc 0x1aeb0b244 0x1aeb06274 0x1aeb05c34 0x1b8c4f38c 0x1b2c3822c 0x10273e2cc 0x1ae98d800)
libc++abi.dylib: terminating with uncaught exception of type NSException 
```

Xcode 11.5
Installed via SPM

**Comment by congnd** [comment]
With the release of v1.0.0, FMPhotoPicker is no longer use xib files to create user interfaces, so you may not face that issue any more. But there is a known issue for loading assets that is not fixed yet. So at this moment, you may not want to use SwiftPM for FMPhotoPicker. But I have a plan to fully support SwiftPM after the release of the next version of Xcode which will be shipped with Swift5.3 that supports loading assets for SwiftPM.
Thanks for reporting this issue. And feel free to reopen it again if you need more support.

https://github.com/congnd/FMPhotoPicker/releases/tag/1.0.0
