### ISSUE TITLE
Error returned from daemon: Error Domain=com.apple.accounts Code=7

### ISSUE THREAD

**Issue by ucelme** [congnd/FMPhotoPicker#43]
I installed FMPhotoPicker on my project, but I get this error when try to apply filters and app crash.

<img width="854" alt="Снимок экрана 2020-06-01 в 17 24 04" src="https://user-images.githubusercontent.com/46785623/83418741-c3e06200-a42c-11ea-84f2-e1e80d74c44f.png">

It seems some kind of conflict with SceneDelegate.swift file.

**Comment by congnd** [comment]
@ucelme 
I couldn't reproduce this error on my side.
Can you provide the sample project?

**Comment by congnd** [comment]
Feel free to reopen if you still need it.
