### ISSUE TITLE
please add a filter category

### ISSUE THREAD

**Issue by janczakb** [congnd/FMPhotoPicker#44]
please add a filter category

**Comment by congnd** [comment]
@janczakb 
Could you provide more detail about your question then I can aswer you better.

**Comment by janczakb** [comment]
@congnd the point is to divide all filters into categories. 

currently, the filters are mixed up, which makes navigation difficult. 

if it were possible to create categories e.g. black & white, portrait, urban, vibrant etc.
![E0685E96-DCC6-492B-B132-D06DE2DEECD4](https://user-images.githubusercontent.com/4959534/83954320-7f97fc00-a848-11ea-8f68-72435eacd4a4.gif)

**Comment by congnd** [comment]
@janczakb 
Thanks for the idea. But I just want to keep FMPhotoPicker to be as simple as possible. So if you need this kind of detailed customization, I think it's better to fork this repo, and then you can add whatever you want.
