### ISSUE TITLE
FMCrop.ratioCustom is available even I put only FMCrop.ratioSquare and forceCropEnabled = true

### ISSUE THREAD

**Issue by Adakhan** [congnd/FMPhotoPicker#47]
`FMCrop.ratioCustom` is available even I put only` FMCrop.ratioSquare` and/or `forceCropEnabled = true`
When I move to Edit image screen, any of FMCrops are not selected and it gives me the opportunity to crop an image as `FMCrop.ratioCustom`

**Comment by congnd** [comment]
Which version you are using and how do you config the editor? Can you post your code here?

**Comment by Adakhan** [comment]
Version 1.1.0
```
config.forceCropEnabled = true
config.availableCrops = [FMCrop.ratioOrigin, FMCrop.ratioSquare]
config.availableFilters = []
```

**Comment by Adakhan** [comment]
my bad, I replaced and now it is works
```
config.forceCropEnabled = true
config.availableCrops = [FMCrop.ratioSquare]
config.availableFilters = []
```

**Comment by congnd** [comment]
Congrats :D
