### ISSUE TITLE
Implementing FMFilterable

### ISSUE THREAD

**Issue by barisnurlu** [congnd/FMPhotoPicker#48]
Hi,

I really appreciate the tremendous work you did. I have couple of extra filters to be added on the slider. However I'm not sure how to add them using FMFilterable. I tried several things but truly speaking couldn't manage smoothly.

If you can support with an example, I really appreciate for that.
Thank you,
Baris

**Comment by congnd** [comment]
Thanks for those kind words. 
Can you post your current configuration here? Then I can give you some suggestion.

**Comment by barisnurlu** [comment]
Hi again,

Into FMFilter.swift file, I've added my new filter, where applicable.

Then, in Const.swift file, I've added new filter name into kDefaultAvailableFilters.

Now at the end of the slide, I can see the new filter name, however it does not have any functionality, and I cannot find where to add the filter code.

**Comment by congnd** [comment]
@barisnurlu 
Can you post your configuration? It's easy for me to understand how you are using the lib.

**Comment by barisnurlu** [comment]
Let me put it in this way. I implemented BBMetalImage pod into my project. It is simply working as following:

let source = BBMetalStaticImageSource(image: myImage!)
source.add(consumer: BBMetalAddBlendFilter())
myImage = BBMetalAddBlendFilter().bbimage

So I want to run this code when user clicks.

**Comment by congnd** [comment]
Firstly, you have to define your custom filters type by adopting the `FMFilterable` protocol.

For example:
```Swift
MyFilter1: FMFilterable {
  func filter(image: UIImage) -> UIImage {
    // do whatever to get the filtered image synchronously.
    // https://github.com/Silence-GitHub/BBMetalImage#process-image-synchronously 
  }
  func filterName() -> String {
    // return the name that will be used in the filter screen
  }  
}
```

Then define all filters you want to use by assigning them to the `availableFilters`.
```Swift
config. availableFilters = [
  MyFilter1(),
  MyFilter2(),
  MyFilter3(),
  // ...
]
```
Then instantiate FMPhotoPicker or FMPhotoEditor
```Swift
let editor = FMImageEditorViewController(config: config, sourceImage: yourImage)

let picker = FMPhotoPickerViewController(config: config)
```

And now you can see your custom filters in the filter screen.

**Comment by barisnurlu** [comment]
I really really appreciate for your support. It did work!

One more question: When I add config.availableFilters = [MyFilter()], it removes all previously built filters. How can I append, instead of overwrite the existing ones.

**Comment by congnd** [comment]
You can config like this:
```Swift
config.availableFilters = [
    FMFilter.None,
    FMFilter.CIPhotoEffectChrome,
    FMFilter.CIPhotoEffectInstant,
    FMFilter.CIPhotoEffectMono,
    FMFilter.CIPhotoEffectProcess,
    FMFilter.CIPhotoEffectTransfer,
    FMFilter.CISepiaTone,
    FMFilter.CIPhotoEffectNoir,
    FMFilter.CIMinimumComponent,
    FMFilter.CIColorPosterize,
    FMFilter.CIColorMonochrome,
    FMFilter.CIColorCrossPolynomial,
    FMFilter.CIColorCube,
    FMFilter.CIColorCubeWithColorSpace,
    FMFilter.CIColorInvert,
    FMFilter.CIFalseColor,
    FMFilter.CIPhotoEffectFade,
    FMFilter.CIPhotoEffectTonal,
    FMFilter.CIVignette, 

    MyFilter1(),
    MyFilter2(),
    MyFilter3(),
    // ...
]
```

**Comment by barisnurlu** [comment]
You are the king! Really appreciate for your support.
