### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by emrdgrmnci** [congnd/FMPhotoPicker#49]
I am trying to add this dependency with Swift Package Manager and I am getting attached error. 

I tried to add with all version rules (up to next major, up to next minor, range, exact) in Xcode

<img width="731" alt="Screen Shot 2020-08-30 at 20 14 06" src="https://user-images.githubusercontent.com/10485498/91665326-66c47d00-eafd-11ea-979b-de6ead2a59ce.png">

**Comment by congnd** [comment]
Let me try and give you feedback.

**Comment by congnd** [comment]
Are you using Xcode 11?
If you want to install FMPhotoPicker via SwiftPM, you must use Xcode 12 and above since there are some feature FMPhotoPicker needs but not be supprted by odler version of SwiftPM. 
For Xcode 11 or older, you can use Carthage or Cocoapod.
