### ISSUE TITLE
CocoaPods installing error

### ISSUE THREAD

**Issue by emrdgrmnci** [congnd/FMPhotoPicker#50]
Version of my iOS project is 13.5 and Swift 5. 

I am getting attached error when I try to install dependency with CocoaPods. 

I also tried to install dependency with Carthage and it is working.

<img width="761" alt="Cocoapods" src="https://user-images.githubusercontent.com/10485498/91702903-10e5e880-eb82-11ea-87e7-bc37ff0d2c98.png">

**Comment by congnd** [comment]
@emrdgrmnci 
Your local pod repo is out of date.
`pod repo update`

Then `pod install` again.

Or simple `pod install --repo-update`

**Comment by emrdgrmnci** [comment]
Ok, solved.
