### ISSUE TITLE
Package Resolution Found 

### ISSUE THREAD

**Issue by abdelmajidrajad** [congnd/FMPhotoPicker#51]
![Screenshot 2020-09-13 at 13 20 11](https://user-images.githubusercontent.com/12987448/93017872-e1909c00-f5c3-11ea-9d14-2db7db3ee1e1.png)

I got this error while trying to add a package manager dependencies on my project. I am using Xcode 11.7 .

**Comment by congnd** [comment]
Please checkout #49
