### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by unixb0y** [congnd/FMPhotoPicker#52]
Hello, I get the following error when building with `carthage update --platform iOS` and having `git "git@github.com:congnd/FMPhotoPicker.git"` in Cartfile:

`Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler`

I use Xcode version 12.0.

**Comment by congnd** [comment]
That's not an issue of FMPhotoPicker. 
The error is quite clear, you may want to recompile FMPhotoPicker with Swift 5.3 which is shipped with Xcode 12.
Make sure that you are using swift 5.3 before running `carthage update`
```
swift --version
```
If you are not using Swift 5.3, you may want to use `xcode-select` to change.

**Comment by unixb0y** [comment]
Thanks, probably `swift` was still using the old compiler since I hadn't rebooted yet after updating Xcode. Today, the error was gone and `swift --version` prints 5.3.

However, now I get 
```Build Failed
	Task failed with exit code 1:
	[...]
```
But when opening the logfile, it says `** BUILD SUCCEEDED **`.

**Comment by congnd** [comment]
Can you show me the full error log?
I guess the issue you are facing may relates to this one. There is no official solution currently, but there is a workaround so you can try it.
https://github.com/Carthage/Carthage/issues/3019

**Comment by unixb0y** [comment]
Yep, it's a Carthage error, sorry! This fixes it: https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5 :)
