### ISSUE TITLE
Image rotation functionality when we edit the image.

### ISSUE THREAD

**Issue by Satish24sp** [congnd/FMPhotoPicker#58]
Hello Team,
I need an Image rotation functionality along with the filter and crop functionalities.
I found the rotation function created inside the FMCropView.swift but it is empty(Screenshot below).

So could you please help me to achieve the desired result. 

![Screenshot 2021-02-03 at 5 07 48 PM](https://user-images.githubusercontent.com/35003745/106742192-b413c000-6642-11eb-966b-e1dd24d994e4.png)

Thanks in advance.

**Comment by Satish24sp** [comment]
Hello Team,

Is this rotate() function is unnecessary or currently in development?

**Comment by Satish24sp** [comment]
Hello Team,

Is this rotate() function is useful or currently in development?

**Comment by congnd** [comment]
Sorry, no rotation support for now
